# This is example for using the codemagic_app_preview package in a
# `codemagic.yaml`.

workflows:
  app_preview:
    name: app_preview
    environment:
      flutter: stable
    scripts:
      - script: echo "Hello"
      - script: flutter --version
